name: test-linter-check

on:
  - push
  - pull_request

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v4
      - name: use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
      - name: install dependencies
        run: make install-in-workflow
      - name: linter check
        run: make lint
      - name: tests check
        run: make test
      - name: check code coverage
        uses:
          paambaati/codeclimate-action@v5.0.0
          # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-cov
          debug: true